name: Build and Upload
on:
  pull_request:
  push:
    branches: ["**"]
    tags: ["**"]
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: true

      - name: Get current date
        id: date
        run: |
          echo "date=$(date +%Y-%m-%d)" >> "$GITHUB_OUTPUT"

      - name: List all files that end with *.typ on the root folder
        id: typst-files
        run: |
          echo "files=$(find . -name '*.typ' -depth 1)" >> "$GITHUB_OUTPUT"

      - name: Typst
        uses: jncfa/typst-action@main
        with:
          source_file: |
            ${{ steps.typst-files.outputs.files }}
          options: |
              --font-path
              fonts
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: "*.pdf"

      - name: Release
        uses: softprops/action-gh-release@v2.2.1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }} — ${{ steps.date.outputs.date }}"
          files: "*.pdf"
